In [2]:
import numpy as np

In [7]:
a = range(100000)
a_np = np.arange(100000)

In [8]:
%timeit [i**2 for i in a]
%timeit a_np**2

28.1 ms ± 890 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
69 µs ± 1.35 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [52]:
arr = list(range(1, 11, 2)) #python range doesn't include second value
np_arr = np.array(arr1)
print(arr*2)
print(np_arr*2)
print(np_arr**2) #doesn't work with python lists

[1, 3, 5, 7, 9, 1, 3, 5, 7, 9]
[ 2  6 10 14 18]
[ 1  9 25 49 81]


In [42]:
print(np_arr.ndim)
print(np_arr.shape)

1
(5,)


In [ ]:
a1 = list(range(1, 11, 2.5)) #Gives error

In [55]:
a1_np = np.arange(1, 11, 2.5)
a1_np

array([1. , 3.5, 6. , 8.5])

In [27]:
print(np.array([1, 2, 3]))
print(np.array([1, 2, 3.41]))
print(np.array([1, 2, "A"]))

[1 2 3]
[1.   2.   3.41]
['1' '2' 'A']


In [32]:
temp = np.array(range(1, 12))
#temp m[-12] --> doesnt work
temp[-11]

1

In [33]:
print(np_arr[[0, 3, 4]]) #providing list of indexes

[1 7 9]


In [87]:
print(np_arr[:3])
print(np_arr[-5:-1])
print(np_arr[-5:4])
print(np_arr[-5:0]) #same element 
print(np_arr[::-1]) #[start:end:step_size]
print(np_arr[3:0:-1]) #includes start index, but excludes the end index.
print(np_arr[0:4:2])
print(np_arr[-4::1])

[1 3 5]
[1 3 5 7]
[1 3 5 7]
[]
[9 7 5 3 1]
[7 5 3]
[1 5]
[3 5 7 9]


In [85]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30])
a[2:] = b[1]
print(a)
a[2:] = b[::-1]
a

[ 1  2 20 20 20]


array([ 1,  2, 30, 20, 10])

<b> Insertion </b>
<br><b> IMP : </b> Numpy append() is <b> NOT <b> In - Place
<br> https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [3]:
outcomes = np.array(["a"])
np.append(outcomes, "b")
np.append(outcomes, "c")
np.append(outcomes, "d")
outcomes

array(['a'], dtype='<U1')

In [4]:
outcomes = np.array(["a"])
outcomes = np.append(outcomes, "b")
outcomes = np.append(outcomes, "c")
outcomes = np.append(outcomes, "d")
outcomes

array(['a', 'b', 'c', 'd'], dtype='<U1')

<b>Fancy Indexing </b><br>
Important read: https://stackoverflow.com/questions/21415661/logical-operators-for-boolean-indexing-in-pandas

In [91]:
a = np.arange(1, 6)
print(a)
a > 3 #boolean mask

[1 2 3 4 5]


array([False, False, False,  True,  True])

In [92]:
a[a>3]

array([4, 5])

In [105]:
a%2 == 0

array([False,  True, False,  True, False])

In [93]:
a[a%2 == 0]

array([2, 4])

In [102]:
a[(a%2 == 0) | (a%5 == 0)] #in numpy and pandas, bitwise operators are overloaded to perform element-wise logical operations

array([2, 4, 5])

<b> Operations on Numpy Array </b>

In [112]:
b = np.arange(10, 15)
print(b+10)

[20 21 22 23 24]


In [113]:
a + b

array([11, 13, 15, 17, 19])

In [117]:
print(np.sum(a))
print(np.min(a))

15
1


<b> Net Promoter Score </b>
<br> NPS = %Promoters - %Detractor

In [126]:
scores = np.loadtxt("./survey.txt", dtype = "int")
print(scores)

[ 7 10  5 ...  5  9 10]


In [154]:
#sanity check
print(scores.shape)
print(min(scores))
print(max(scores))
print(np.unique(scores))

(1167,)
1
10
[ 1  4  5  7  8  9 10]


In [152]:
num_detractors = scores[scores <= 6].shape[0]
print(num_detractors)
num_promoters = scores[scores >= 9].shape[0]
print(num_promoters)
num_passive = scores[(scores < 9) & (scores > 6)].shape[0]
print(num_passive)
perc_det = num_detractors/scores.shape[0]*100
perc_prom = num_promoters/scores.shape[0]*100
print("% detractors = ", perc_det, "\n% promoters = ", perc_prom)

332
609
226
% detractors =  28.449014567266495 
% promoters =  52.185089974293064


In [148]:
nps = perc_prom - perc_det
round(nps, 0)

24.0