In [2]:
import numpy as np

<h2> Splitting </h2>

In [9]:
x = np.arange(9)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [6]:
np.split(x, 3)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [4]:
np.split(x, [3, 5, 6]) #splits array at index 3, 5, 6

[array([0, 1, 2]), array([3, 4]), array([5]), array([6, 7, 8])]

In [4]:
x1 = np.arange(16).reshape(4, 4)
x1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [49]:
np.split(x1, 2, axis = 1)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [12]:
np.split(x1, 4, axis = 0)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

<h2> Stacking </h2>

In [6]:
temp = np.stack([x1]*3, axis = 0)
print(temp.shape)
print("\n", temp)

(3, 4, 4)

 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]]


In [54]:
temp = np.vstack([x1]*3)
print(temp.shape)
print("\n", temp)

(12, 4)

 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [7]:
temp = np.stack([x1]*3, axis = 1)
print(temp.shape)
print("\n", temp)

(4, 3, 4)

 [[[ 0  1  2  3]
  [ 0  1  2  3]
  [ 0  1  2  3]]

 [[ 4  5  6  7]
  [ 4  5  6  7]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [ 8  9 10 11]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [12 13 14 15]
  [12 13 14 15]]]


In [8]:
temp = np.hstack([x1]*3)
print(temp.shape)
print("\n", temp)

(4, 12)

 [[ 0  1  2  3  0  1  2  3  0  1  2  3]
 [ 4  5  6  7  4  5  6  7  4  5  6  7]
 [ 8  9 10 11  8  9 10 11  8  9 10 11]
 [12 13 14 15 12 13 14 15 12 13 14 15]]


<b> 
<br> During concatenation, the arrays must have the same shape, they won't be implicitly broadcasted. So, an 1d array cannot be concatenated with a 2d and vice-versa. 
    <li> if we are concatenating on axis=0 (one below the other), num. of columns should be equal </li>
    <li> if we are concatenating on axis=1 (one on the right of another), num. of rows must be equal </li>
<br> During hstack(), the number of rows of the two matrices used should be equal 
<br> During vstack(), the number of columns of the two matrices used should be equal 
</b>

In [45]:
x2 = np.arange(4).reshape(1, 4)
print(x2)
np.vstack((x1, x2)) 

[[0 1 2 3]]


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [ 0,  1,  2,  3]])

<h2> Broadcasting </h2>

In [31]:
np.stack([np.arange(0, 31, 10)]*4, axis = 0)

array([[ 0, 10, 20, 30],
       [ 0, 10, 20, 30],
       [ 0, 10, 20, 30],
       [ 0, 10, 20, 30]])

In [34]:
np.tile(np.arange(0, 31, 10), (4, 1))

array([[ 0, 10, 20, 30],
       [ 0, 10, 20, 30],
       [ 0, 10, 20, 30],
       [ 0, 10, 20, 30]])

In [36]:
m1 = np.arange(0, 31, 10).reshape(-1, 1)
print(m1)
m2 = np.arange(0, 3)
print("\n", m2)
print("\n", m1 + m2)

[[ 0]
 [10]
 [20]
 [30]]

 [0 1 2]

 [[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


In [41]:
np.shares_memory(m1, m2)

False

In [13]:
x1[:, [0]]

array([[ 0],
       [ 4],
       [ 8],
       [12]])

In [14]:
x1[:, 0]

array([ 0,  4,  8, 12])