In [2]:
import numpy as np

In [14]:
a1 = ([1, 2, 3], [4, 5, 6])
arr = np.array(a1)
print(arr.ndim)
print(arr.shape)

2
(2, 3)


In [16]:
np.arange(1, 13).reshape(4, 3) 
#only works with factors of 12 (num of elements)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [31]:
print(np.arange(1, 13).reshape(1, 12)) #not a 1d array
print(len(np.arange(1, 13).reshape(1, 12)))
print(np.arange(1, 13).reshape(12, 1)) 
print(len(np.arange(1, 13).reshape(12, 1)))

[[ 1  2  3  4  5  6  7  8  9 10 11 12]]
1
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]
12


In [35]:
#to convert 2d array back to 1d array, we use flatten()
a = np.arange(1, 13).reshape(2, 6)
print(a, "\n")
flat = a.flatten()
ravel = a.ravel()
print("flattened array: ", flat)
print("ravelled array: ", ravel)
print(flat.base)
print(ravel.base)
#If it's a view, the base will be the original array; 
# if it is a copy, the base will be None.

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]] 

flattened array:  [ 1  2  3  4  5  6  7  8  9 10 11 12]
ravelled array:  [ 1  2  3  4  5  6  7  8  9 10 11 12]
None
[ 1  2  3  4  5  6  7  8  9 10 11 12]


<b> Transpose </b>

In [29]:
a = np.array([[1, 2], [3, 4]])
print(a, "\n")
print(a.T) # same as a.transpose()

[[1 2]
 [3 4]] 

[[1 3]
 [2 4]]


<b> Indexing and Slicing 2d array </b>

In [12]:
m1 = np.arange(1, 10000).reshape(3, 33, 101)
m1

array([[[   1,    2,    3, ...,   99,  100,  101],
        [ 102,  103,  104, ...,  200,  201,  202],
        [ 203,  204,  205, ...,  301,  302,  303],
        ...,
        [3031, 3032, 3033, ..., 3129, 3130, 3131],
        [3132, 3133, 3134, ..., 3230, 3231, 3232],
        [3233, 3234, 3235, ..., 3331, 3332, 3333]],

       [[3334, 3335, 3336, ..., 3432, 3433, 3434],
        [3435, 3436, 3437, ..., 3533, 3534, 3535],
        [3536, 3537, 3538, ..., 3634, 3635, 3636],
        ...,
        [6364, 6365, 6366, ..., 6462, 6463, 6464],
        [6465, 6466, 6467, ..., 6563, 6564, 6565],
        [6566, 6567, 6568, ..., 6664, 6665, 6666]],

       [[6667, 6668, 6669, ..., 6765, 6766, 6767],
        [6768, 6769, 6770, ..., 6866, 6867, 6868],
        [6869, 6870, 6871, ..., 6967, 6968, 6969],
        ...,
        [9697, 9698, 9699, ..., 9795, 9796, 9797],
        [9798, 9799, 9800, ..., 9896, 9897, 9898],
        [9899, 9900, 9901, ..., 9997, 9998, 9999]]])

In [15]:
%timeit m1[1][15][51]
%timeit m1[1, 15, 51]
#as we can see the second operation is much faster, because the first
#operation is a 3-step process: first gets the depth, then the row
#then moves onto the column element
#whereas, in the second operations, the compiler is more optimized

854 ns ± 21.8 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
325 ns ± 14.5 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [23]:
x1=np.arange(0,24).reshape(6,4)
print(x1)
print("\n", x1[:][1])
print(x1[:,1])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

 [4 5 6 7]
[ 1  5  9 13 17 21]


In [53]:
m1 = np.arange(1, 10).reshape(3, 3)
print(m1)
print("\n", m1[[0, 1]])
print("\n", m1[[0, 1, 2], [0, 1, 2]])

[[1 2 3]
 [4 5 6]
 [7 8 9]]

 [[1 2 3]
 [4 5 6]]

 [1 5 9]


In [56]:
print(m1[:2])
print("\n", m1[:, :2])
print("\n", m1[1:, 1:])

[[1 2 3]
 [4 5 6]]

 [[1 2]
 [4 5]
 [7 8]]

 [[5 6]
 [8 9]]


In [32]:
m2 = np.arange(1, 13).reshape(3, 4)
print(m2)
print("\n Odd columns - specific: \n", m2[:, [1, 3]])
print("\n Odd columns with step-size: \n", m2[:, 1::2]) #step-size = 2
print("\n", m2[:, 1:4:2])
print("\n Last 2 columns: \n", m2[:, -2:])
print("\n Last 2 columns with step-size: \n", m2[:, -2::1])
print("\n Reverse column-wise: \n", m2[:, ::-1])
print("\n Reverse row-wise: \n", m2[::-1, :])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

 Odd columns - specific: 
 [[ 2  4]
 [ 6  8]
 [10 12]]

 Odd columns with step-size: 
 [[ 2  4]
 [ 6  8]
 [10 12]]

 [[ 2  4]
 [ 6  8]
 [10 12]]

 Last 2 columns: 
 [[ 3  4]
 [ 7  8]
 [11 12]]

 Last 2 columns with step-size: 
 [[ 3  4]
 [ 7  8]
 [11 12]]

 Reverse column-wise: 
 [[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]

 Reverse row-wise: 
 [[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [65]:
m2[[0, 2], 0:2]

array([[ 1,  2],
       [ 9, 10]])

<b> Fancing Indexing </b>

In [83]:
print(m2 < 6)
print("\n", m2[m2 < 6]) # answering of filtering is one-dimensional

[[ True  True  True  True]
 [ True False False False]
 [False False False False]]

 [1 2 3 4 5]


<b> Universal Functions

In [88]:
#Arithmetic Operations
print("\n",m2.sum()) #sum of all elements, same as np.sum(m2)
print("\n",sum(m2)) #column wise sum
print(np.sum(m2, axis = 0)) #axis = 0 --> columnwise
print(np.sum(m2, axis = 1)) #axis = 1 --> row-wise
print("\n", np.sort(m2, axis = 0)[::-1])


 78

 [15 18 21 24]
[15 18 21 24]
[10 26 42]

 [[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [41]:
#Logical Operations
a = np.arange(1, 6)
b = np.arange(5, 0, -1)
print(a, b)
a > b

[1 2 3 4 5] [5 4 3 2 1]


array([False, False, False,  True,  True])

In [42]:
print(np.all(a>b))
print(np.any(a>b))

False
True


In [43]:
if np.any(a <= 3):
    print ("condition satisfies")
else:
    print ("condition doesn't satisfy")

condition satisfies


In [68]:
print(np.where(a >= 3))
print(type(np.where(a >= 3)))
print(len(np.where(a >= 3)))
b[np.where(a>=3)] #since the length is '1', we don't have to mentioned np.where(a>=3)[0]

(array([2, 3, 4], dtype=int64),)
<class 'tuple'>
1


array([3, 2, 1])

In [69]:
print(np.argwhere(a >= 3))

[[2]
 [3]
 [4]]


In [4]:
m = np.array([[5, 3, 9],[2, 1, 4],[7, 6, 8]])
m

array([[5, 3, 9],
       [2, 1, 4],
       [7, 6, 8]])

In [103]:
np.argsort(m[:, 1])

array([1, 0, 2], dtype=int64)

In [39]:
m[np.argsort(m[:, 1])] #sorted by 2nd column

array([[2, 1, 4],
       [5, 3, 9],
       [7, 6, 8]])

In [107]:
np.dot(m, 10)

array([[50, 30, 90],
       [20, 10, 40],
       [70, 60, 80]])

<b><u>Main difference where and argwhere is that: </b></u>
<li> Where is better for if-else conditions [np.where(arr, if-cond, else-cond)] </li>
<li> For arrays above 2 dimensions, np.where gives tuples as an answer, instead argwhere gives the tranpose of the same tuple which is much easier to interpret and use </li>
<li> For 1-d arrays both give similar results but np.where is more readable (check above) </li>

[stackoverflow](https://stackoverflow.com/questions/35796513/from-argwhere-to-where) 
<br>[np.where doc](https://numpy.org/doc/stable/reference/generated/numpy.where.html)
<br>[np.argwhere doc](https://numpy.org/doc/stable/reference/generated/numpy.argwhere.html)

In [19]:
np.where(m >= 5)

(array([0, 0, 2, 2, 2], dtype=int64), array([0, 2, 0, 1, 2], dtype=int64))

In [9]:
np.argwhere(m >= 5)

array([[0, 0],
       [0, 2],
       [2, 0],
       [2, 1],
       [2, 2]], dtype=int64)